//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  caseStudy: CaseStudy;
  caseStudyConnection: CaseStudyConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryCaseStudyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCaseStudyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CaseStudyFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  caseStudy?: InputMaybe<CaseStudyFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | CaseStudy | Folder;

export type HomeWork = {
  __typename?: 'HomeWork';
  title?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  companies?: Maybe<Scalars['String']['output']>;
};

export type HomeProjects = {
  __typename?: 'HomeProjects';
  title?: Maybe<Scalars['String']['output']>;
  company?: Maybe<Scalars['String']['output']>;
  preview?: Maybe<Scalars['String']['output']>;
  caseSlug?: Maybe<Scalars['String']['output']>;
};

export type HomeThoughts = {
  __typename?: 'HomeThoughts';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type HomeContact = {
  __typename?: 'HomeContact';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  name: Scalars['String']['output'];
  tagline?: Maybe<Scalars['String']['output']>;
  work?: Maybe<HomeWork>;
  canopyTitle?: Maybe<Scalars['String']['output']>;
  projects?: Maybe<Array<Maybe<HomeProjects>>>;
  thoughtsTitle?: Maybe<Scalars['String']['output']>;
  thoughtsNote?: Maybe<Scalars['String']['output']>;
  thoughts?: Maybe<Array<Maybe<HomeThoughts>>>;
  contact?: Maybe<Array<Maybe<HomeContact>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeWorkFilter = {
  title?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  companies?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  preview?: InputMaybe<ImageFilter>;
  caseSlug?: InputMaybe<StringFilter>;
};

export type HomeThoughtsFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type HomeContactFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  work?: InputMaybe<HomeWorkFilter>;
  canopyTitle?: InputMaybe<StringFilter>;
  projects?: InputMaybe<HomeProjectsFilter>;
  thoughtsTitle?: InputMaybe<StringFilter>;
  thoughtsNote?: InputMaybe<StringFilter>;
  thoughts?: InputMaybe<HomeThoughtsFilter>;
  contact?: InputMaybe<HomeContactFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type CaseStudyHero = {
  __typename?: 'CaseStudyHero';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type CaseStudyBody = {
  __typename?: 'CaseStudyBody';
  style?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type CaseStudyCards = {
  __typename?: 'CaseStudyCards';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type CaseStudySectionsMedia = {
  __typename?: 'CaseStudySectionsMedia';
  image?: Maybe<Scalars['String']['output']>;
  video?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type CaseStudySectionsStats = {
  __typename?: 'CaseStudySectionsStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type CaseStudySections = {
  __typename?: 'CaseStudySections';
  title?: Maybe<Scalars['String']['output']>;
  media?: Maybe<CaseStudySectionsMedia>;
  body?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<CaseStudySectionsStats>>>;
};

export type CaseStudy = Node & Document & {
  __typename?: 'CaseStudy';
  slug: Scalars['String']['output'];
  locked?: Maybe<Scalars['Boolean']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<CaseStudyHero>;
  index?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Array<Maybe<CaseStudyBody>>>;
  cards?: Maybe<Array<Maybe<CaseStudyCards>>>;
  closing?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<CaseStudySections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type CaseStudyHeroFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type CaseStudyBodyFilter = {
  style?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type CaseStudyCardsFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type CaseStudySectionsMediaFilter = {
  image?: InputMaybe<ImageFilter>;
  video?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type CaseStudySectionsStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type CaseStudySectionsFilter = {
  title?: InputMaybe<StringFilter>;
  media?: InputMaybe<CaseStudySectionsMediaFilter>;
  body?: InputMaybe<StringFilter>;
  stats?: InputMaybe<CaseStudySectionsStatsFilter>;
};

export type CaseStudyFilter = {
  slug?: InputMaybe<StringFilter>;
  locked?: InputMaybe<BooleanFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  hero?: InputMaybe<CaseStudyHeroFilter>;
  index?: InputMaybe<StringFilter>;
  body?: InputMaybe<CaseStudyBodyFilter>;
  cards?: InputMaybe<CaseStudyCardsFilter>;
  closing?: InputMaybe<StringFilter>;
  sections?: InputMaybe<CaseStudySectionsFilter>;
};

export type CaseStudyConnectionEdges = {
  __typename?: 'CaseStudyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CaseStudy>;
};

export type CaseStudyConnection = Connection & {
  __typename?: 'CaseStudyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CaseStudyConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateCaseStudy: CaseStudy;
  createCaseStudy: CaseStudy;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateCaseStudyArgs = {
  relativePath: Scalars['String']['input'];
  params: CaseStudyMutation;
};


export type MutationCreateCaseStudyArgs = {
  relativePath: Scalars['String']['input'];
  params: CaseStudyMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  caseStudy?: InputMaybe<CaseStudyMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  caseStudy?: InputMaybe<CaseStudyMutation>;
};

export type HomeWorkMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  companies?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  preview?: InputMaybe<Scalars['String']['input']>;
  caseSlug?: InputMaybe<Scalars['String']['input']>;
};

export type HomeThoughtsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type HomeContactMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  work?: InputMaybe<HomeWorkMutation>;
  canopyTitle?: InputMaybe<Scalars['String']['input']>;
  projects?: InputMaybe<Array<InputMaybe<HomeProjectsMutation>>>;
  thoughtsTitle?: InputMaybe<Scalars['String']['input']>;
  thoughtsNote?: InputMaybe<Scalars['String']['input']>;
  thoughts?: InputMaybe<Array<InputMaybe<HomeThoughtsMutation>>>;
  contact?: InputMaybe<Array<InputMaybe<HomeContactMutation>>>;
};

export type CaseStudyHeroMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type CaseStudyBodyMutation = {
  style?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type CaseStudyCardsMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type CaseStudySectionsMediaMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type CaseStudySectionsStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type CaseStudySectionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  media?: InputMaybe<CaseStudySectionsMediaMutation>;
  body?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<CaseStudySectionsStatsMutation>>>;
};

export type CaseStudyMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  locked?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<CaseStudyHeroMutation>;
  index?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Array<InputMaybe<CaseStudyBodyMutation>>>;
  cards?: InputMaybe<Array<InputMaybe<CaseStudyCardsMutation>>>;
  closing?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<CaseStudySectionsMutation>>>;
};

export type HomePartsFragment = { __typename: 'Home', name: string, tagline?: string | null, canopyTitle?: string | null, thoughtsTitle?: string | null, thoughtsNote?: string | null, work?: { __typename: 'HomeWork', title?: string | null, role?: string | null, companies?: string | null } | null, projects?: Array<{ __typename: 'HomeProjects', title?: string | null, company?: string | null, preview?: string | null, caseSlug?: string | null } | null> | null, thoughts?: Array<{ __typename: 'HomeThoughts', title?: string | null, image?: string | null } | null> | null, contact?: Array<{ __typename: 'HomeContact', label?: string | null, href?: string | null } | null> | null };

export type CaseStudyPartsFragment = { __typename: 'CaseStudy', slug: string, locked?: boolean | null, title: string, subtitle?: string | null, index?: Array<string | null> | null, closing?: string | null, hero?: { __typename: 'CaseStudyHero', src?: string | null, alt?: string | null } | null, body?: Array<{ __typename: 'CaseStudyBody', style?: string | null, text?: string | null } | null> | null, cards?: Array<{ __typename: 'CaseStudyCards', src?: string | null, alt?: string | null } | null> | null, sections?: Array<{ __typename: 'CaseStudySections', title?: string | null, body?: string | null, media?: { __typename: 'CaseStudySectionsMedia', image?: string | null, video?: string | null, alt?: string | null } | null, stats?: Array<{ __typename: 'CaseStudySectionsStats', value?: string | null, label?: string | null } | null> | null } | null> | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, name: string, tagline?: string | null, canopyTitle?: string | null, thoughtsTitle?: string | null, thoughtsNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, work?: { __typename: 'HomeWork', title?: string | null, role?: string | null, companies?: string | null } | null, projects?: Array<{ __typename: 'HomeProjects', title?: string | null, company?: string | null, preview?: string | null, caseSlug?: string | null } | null> | null, thoughts?: Array<{ __typename: 'HomeThoughts', title?: string | null, image?: string | null } | null> | null, contact?: Array<{ __typename: 'HomeContact', label?: string | null, href?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, name: string, tagline?: string | null, canopyTitle?: string | null, thoughtsTitle?: string | null, thoughtsNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, work?: { __typename: 'HomeWork', title?: string | null, role?: string | null, companies?: string | null } | null, projects?: Array<{ __typename: 'HomeProjects', title?: string | null, company?: string | null, preview?: string | null, caseSlug?: string | null } | null> | null, thoughts?: Array<{ __typename: 'HomeThoughts', title?: string | null, image?: string | null } | null> | null, contact?: Array<{ __typename: 'HomeContact', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export type CaseStudyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CaseStudyQuery = { __typename?: 'Query', caseStudy: { __typename: 'CaseStudy', id: string, slug: string, locked?: boolean | null, title: string, subtitle?: string | null, index?: Array<string | null> | null, closing?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'CaseStudyHero', src?: string | null, alt?: string | null } | null, body?: Array<{ __typename: 'CaseStudyBody', style?: string | null, text?: string | null } | null> | null, cards?: Array<{ __typename: 'CaseStudyCards', src?: string | null, alt?: string | null } | null> | null, sections?: Array<{ __typename: 'CaseStudySections', title?: string | null, body?: string | null, media?: { __typename: 'CaseStudySectionsMedia', image?: string | null, video?: string | null, alt?: string | null } | null, stats?: Array<{ __typename: 'CaseStudySectionsStats', value?: string | null, label?: string | null } | null> | null } | null> | null } };

export type CaseStudyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CaseStudyFilter>;
}>;


export type CaseStudyConnectionQuery = { __typename?: 'Query', caseStudyConnection: { __typename?: 'CaseStudyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CaseStudyConnectionEdges', cursor: string, node?: { __typename: 'CaseStudy', id: string, slug: string, locked?: boolean | null, title: string, subtitle?: string | null, index?: Array<string | null> | null, closing?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'CaseStudyHero', src?: string | null, alt?: string | null } | null, body?: Array<{ __typename: 'CaseStudyBody', style?: string | null, text?: string | null } | null> | null, cards?: Array<{ __typename: 'CaseStudyCards', src?: string | null, alt?: string | null } | null> | null, sections?: Array<{ __typename: 'CaseStudySections', title?: string | null, body?: string | null, media?: { __typename: 'CaseStudySectionsMedia', image?: string | null, video?: string | null, alt?: string | null } | null, stats?: Array<{ __typename: 'CaseStudySectionsStats', value?: string | null, label?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  name
  tagline
  work {
    __typename
    title
    role
    companies
  }
  canopyTitle
  projects {
    __typename
    title
    company
    preview
    caseSlug
  }
  thoughtsTitle
  thoughtsNote
  thoughts {
    __typename
    title
    image
  }
  contact {
    __typename
    label
    href
  }
}
    `;
export const CaseStudyPartsFragmentDoc = gql`
    fragment CaseStudyParts on CaseStudy {
  __typename
  slug
  locked
  title
  subtitle
  hero {
    __typename
    src
    alt
  }
  index
  body {
    __typename
    style
    text
  }
  cards {
    __typename
    src
    alt
  }
  closing
  sections {
    __typename
    title
    media {
      __typename
      image
      video
      alt
    }
    body
    stats {
      __typename
      value
      label
    }
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const CaseStudyDocument = gql`
    query caseStudy($relativePath: String!) {
  caseStudy(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CaseStudyParts
  }
}
    ${CaseStudyPartsFragmentDoc}`;
export const CaseStudyConnectionDocument = gql`
    query caseStudyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CaseStudyFilter) {
  caseStudyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CaseStudyParts
      }
    }
  }
}
    ${CaseStudyPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    caseStudy(variables: CaseStudyQueryVariables, options?: C): Promise<{data: CaseStudyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyQueryVariables, query: string}> {
        return requester<{data: CaseStudyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyQueryVariables, query: string}, CaseStudyQueryVariables>(CaseStudyDocument, variables, options);
      },
    caseStudyConnection(variables?: CaseStudyConnectionQueryVariables, options?: C): Promise<{data: CaseStudyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyConnectionQueryVariables, query: string}> {
        return requester<{data: CaseStudyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyConnectionQueryVariables, query: string}, CaseStudyConnectionQueryVariables>(CaseStudyConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  